version: '3.8'
services:
  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: streaming_app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
